### ISSUE TITLE
Loss of Type Safety When Selecting All Columns Without Asterisk in jOOQ Versions 3.19 and 3.20

### ISSUE THREAD

**Issue by algrantcompass** [jOOQ/jOOQ#18273]
### Expected behavior

In JOOQ versions 3.19 and 3.20, we are unable to explicitly select all columns available from a table using no asterisk.

We are using embedded key support from JOOQ Express Edition.

The docs say it should be possible: https://www.jooq.org/doc/3.20/manual/sql-building/sql-statements/select-statement/select-clause/select-clause-asterisk/

This was possible in version 18, and it was type-safe.

In version 3.19 and 3.20, we have to use an explicit qualified asterisk, and the record is no longer type-safe. It yields a `Result<Record!>`.

Type safety is a priority for us, and it seems like the only way to maintain it is to explicitly select individual fields, but there are plenty of use cases for us where we do want all columns, and our options are now to use `.asterisk()` and lose type safety or have very verbose code.

Can you confirm if the docs are wrong, and we should still be able to select all columns with no asterisk? 

### Actual behavior

Query all cols explicitly.

<img width="1043" alt="Image" src="https://github.com/user-attachments/assets/2a1fe5f3-6bf8-45b2-8b69-d0b991045f58" />
<img width="1208" alt="Image" src="https://github.com/user-attachments/assets/cf92947b-0039-47b1-b46d-35528e4b97fd" />

Query No asterisk

<img width="1164" alt="Image" src="https://github.com/user-attachments/assets/10b4a10b-b8cb-4cd4-80ac-cfe1f2e486b9" />

Query with asterisk, not type safe.

<img width="1120" alt="Image" src="https://github.com/user-attachments/assets/f93dda6a-66b8-42cd-b2d5-96359d1df89b" />
<img width="1145" alt="Image" src="https://github.com/user-attachments/assets/ce0d0b3b-2843-4dd7-acc7-3ef1fd3c0885" />

JOOQ docs

<img width="1864" alt="Image" src="https://github.com/user-attachments/assets/a1015343-71e3-4a91-a28c-d3c35862bfab" />

### Steps to reproduce the problem

Docs indicate it should work, but it is not possible. It did work in version 3.18 and was type safe.

Type mismatch.
Required:
SelectField<TypeVariable(T2)!>!
Found:
DoSpace!

```
val dbData = dslContext
    .select(DO_REPLACE_SPACE_ACTION.PK__DO_REPLACE_SPACE_ACTION, DO_SPACE)
    .from(DO_SPACE)
    .join(DO_REPLACE_SPACE_ACTION)
    .on(DO_SPACE.PK__DO_SPACE.eq(DO_REPLACE_SPACE_ACTION.FK__DO_REPLACE_SPACE_ACTION__OLD_DO_SPACE))
    .where(DO_REPLACE_SPACE_ACTION.PK__DO_REPLACE_SPACE_ACTION.`in`(ids.map { it.asEmbeddableRecord() }))
    .fetch()
```

Works ibn versions 3.19 and 3.20, but it is not type safe.

Results in:

`dbData: Result<Record!>`

```
val dbData = dslContext
    .select(DO_REPLACE_SPACE_ACTION.PK__DO_REPLACE_SPACE_ACTION, DO_SPACE.asterisk())
    .from(DO_SPACE)
    .join(DO_REPLACE_SPACE_ACTION)
    .on(DO_SPACE.PK__DO_SPACE.eq(DO_REPLACE_SPACE_ACTION.FK__DO_REPLACE_SPACE_ACTION__OLD_DO_SPACE))
    .where(DO_REPLACE_SPACE_ACTION.PK__DO_REPLACE_SPACE_ACTION.`in`(ids.map { it.asEmbeddableRecord() }))
    .fetch()
```

Works in versions 3.19 and 3.20 and is type-safe, but can get very verbose.

```
val dbData = dslContext
    .select(
        DO_REPLACE_SPACE_ACTION.PK__DO_REPLACE_SPACE_ACTION,
        DO_SPACE.PK__DO_SPACE,
        DO_SPACE.ARCHIVED,
        DO_SPACE.CAPACITY,
        DO_SPACE.UK__DO_SPACE__WORKING_SET_ID__CODE,
        DO_SPACE.SOURCE_TIMETABLE_WORKING_SET_ID,
        DO_SPACE.YARD_DUTY,
        DO_SPACE.FK__DO_SPACE__ROOM_WORKING_SET_ID__ROOM_ENTITY_ID,
        DO_SPACE.TYPE,
        DO_SPACE.IMPORT_ENTITY_ID
    )
    .from(DO_SPACE)
    .join(DO_REPLACE_SPACE_ACTION)
    .on(DO_SPACE.PK__DO_SPACE.eq(DO_REPLACE_SPACE_ACTION.FK__DO_REPLACE_SPACE_ACTION__OLD_DO_SPACE))
    .where(DO_REPLACE_SPACE_ACTION.PK__DO_REPLACE_SPACE_ACTION.`in`(ids.map { it.asEmbeddableRecord() }))
    .fetch()
```

### jOOQ Version

3.20.2

### Database product and version

PostgreSQL 13

### Java Version

OpenJDK Runtime Environment Corretto-17.0.14.7.1 (build 17.0.14+7-LTS)

### JDBC / R2DBC driver name and version (include name if unofficial driver)

org/postgresql:postgresql:42.3.10

**Comment by lukaseder** [comment]
Thanks for your report. The issue template was asking for a reproducer, ideally using our template here: https://github.com/jOOQ/jOOQ-mcve

The point of such reproducers is to clearly convey the bug in a non-ambiguous way. I can see the compilation error in your screenshot, but I really cannot reproduce it, as mentioned by email already. Here's my attempt on the MCVE template:

```patch
diff --git a/jOOQ-mcve-kotlin-h2/src/test/kotlin/org/jooq/mcve/test/kotlin/h2/KotlinTest.kt b/jOOQ-mcve-kotlin-h2/src/test/kotlin/org/jooq/mcve/test/kotlin/h2/KotlinTest.kt
index 5309711..62425a4 100644
--- a/jOOQ-mcve-kotlin-h2/src/test/kotlin/org/jooq/mcve/test/kotlin/h2/KotlinTest.kt
+++ b/jOOQ-mcve-kotlin-h2/src/test/kotlin/org/jooq/mcve/test/kotlin/h2/KotlinTest.kt
@@ -1,7 +1,10 @@
 package org.jooq.mcve.test.kotlin.h2

 import org.jooq.DSLContext
+import org.jooq.Record2
+import org.jooq.Result
 import org.jooq.impl.DSL
+import org.jooq.mcve.kotlin.h2.tables.records.TestRecord
 import org.jooq.mcve.kotlin.h2.tables.references.TEST
 import org.junit.After
 import org.junit.Assert.assertEquals
@@ -40,6 +43,11 @@ class KotlinTest {
             .execute()
         )

+        val result: Result<Record2<Int?, TestRecord>> =
+        ctx().select(TEST.ID, TEST)
+            .from(TEST)
+            .fetch()
+
         val record = ctx().fetchOne(TEST, TEST.CD.eq(42))
         assertNotNull(record?.id)
     }
```

This compiles just fine and produces this query:

```
Executing query          : select "MCVE"."TEST"."ID", "MCVE"."TEST"."ID" "TEST.ID", "MCVE"."TEST"."CD" "TEST.CD" from "MCVE"."TEST"
Fetched result           : +----+-------+                                                                                          
                         : |  ID|TEST   |                                                                                          
                         : +----+-------+                                                                                          
                         : |   1|(1, 42)|                                                                                          
                         : +----+-------+                                                                                          
```

I've also tried using the `JavaGenerator` instead of the `KotlinGenerator` (which is what you're apparently doing, assessing from the screenshots, but it's hard to say these things from screenshots alone, reproducers would be much better!), but that still doesn't reproduce the problem. In fact, this would be such a tremendous regression, we'd be flooded with bug reports if that was really a very obvious bug, so I'm assuming something very subtle is going on.

Can you please provide a completely self contained reproducer?

**Comment by lukaseder** [comment]
I mean, my best guess is that you're using a set of kotlin compiler flags (possibly experimental), which trigger this error, but I couldn't tell from screenshots alone.

**Comment by algrantcompass** [comment]
Hi Lukas. It seems it was a classpath resolution issue. Updating our Spring Boot dependency to exclude the older Jooq versions seems to have resolved the issue.

```groovy
    implementation('org.springframework.boot:spring-boot-starter-jooq') {
        exclude group: 'org.jooq', module: 'jooq'
        exclude group: 'org.jooq', module: 'jooq-meta'
    }
```

**Comment by lukaseder** [comment]
Thanks for following up. I'm glad you could resolve the issue on your end.
