### ISSUE TITLE
UpdatableRecordImpl no longer work when globalObjectReferences is set to false

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#7554]
This is a regression introduced with #5537 in jOOQ 3.11. While there is no compilation error in generated code, the code doesn't work at runtime, as the primary key information is completely missing.

The workaround is to turn on:

```xml
<globalObjectReferences>true</globalObjectReferences>
```

----
See: https://groups.google.com/forum/#!topic/jooq-user/-ILukM1EvlM

**Comment by lukaseder** [comment]
The global key references are important to maintain a type safe model of the primary / foreign key relationships. Removing the `Keys.java` class means that:

- Its functionality has to be reproduced from within the tables, which is difficult
- 
- UpdatableRecords are not possible at all
