### ISSUE TITLE
Avoid optional org.jetbrains.annotations annotations on code generation base classes due to javac annotation processing flaw

### ISSUE THREAD

**Issue by mnisius** [jOOQ/jOOQ#17912]
### Expected behavior

No compile Errors when upgrading from jOOQ 3.18.x to 3.19.x

### Actual behavior

Compile errors in Projects that generated Code from UDTs

### Steps to reproduce the problem

We are currently upgrading from jOOQ 3.18.x to 3.19.x and facing compile errors in some projects. 
 
All projects that generated UDTs seem to require the `org.jetbrains.annotations` package on the classpath. If the library is not present a compile error is thrown. 

Is this onpurpose? I couldn't find any information on the documentation. The root cause of the Problem is the class `org.org.jooq.impl.UDTImpl`. This class is extended from the generated Code and is annotated with `@org.jetbrains.annotations.ApiStatus.Internal`.

 Other subclasses of generated Code, like for example `UDTRecordImpl`, are annotated with `@org.jooq.Internal` and don't cause any Problems

### jOOQ Version

3.19.x

### Database product and version

Oracle 19

### Java Version

21

### JDBC / R2DBC driver name and version (include name if unofficial driver)

com.oracle.database.jdbc.ojdbc8

**Comment by lukaseder** [comment]
Thanks for your report. What is the exact error? How can it be reproduced?

The annotation dependency is declared `provided` and `optional`. As such, and due to the nature of annotations in Java, they shouldn't produce compilation errors. IF you encounter any compilation error, this is likely due to some (non-jOOQ) annotation processor on your class path that behaves incorrectly.

**Comment by lukaseder** [comment]
> Other subclasses of generated Code, like for example `UDTRecordImpl`, are annotated with `@org.jooq.Internal` and don't cause any Problems

That's a bug, I'd say. We shouldn't be using our own `@Internal` annotation anymore, as per jOOQ 3.17:

- https://github.com/jOOQ/jOOQ/issues/13071

I've created:

- https://github.com/jOOQ/jOOQ/issues/17914

**Comment by mnisius** [comment]
Hello, yes you are right. 

The compile errors are caused by annotation processors. We use [immutables ](https://github.com/immutables/immutables) . But after disabling all annotation processors I get the next build error because of the [enunciate](https://github.com/stoicflame/enunciate) maven plugin. 

Are these actual bugs in these components or is that just what happens if something scans your code for annotations? Because for me it basically means to manually add 

```xml
<dependency>
  <groupId>org.jetbrains</groupId>
  <artifactId>annotations</artifactId>
</dependency>

```
to all our projects. 

From a end user perspective I think it would be much easier if this dependency wouldn't be optional in jOOQ because then this problem wouldn't' occur in the first place.

**Comment by lukaseder** [comment]
> From a end user perspective I think it would be much easier if this dependency wouldn't be optional in jOOQ because then this problem wouldn't' occur in the first place.

Well,  but it *is* an optional dependency. You don't need it to make your code work. Using jOOQ with vanilla  javac and without the explicit dependency works out of the box.

If jOOQ is requested to make a workaround, then these issues are never fixed where they should be,  i.e. in those two libraries that you've mentioned (there are probably others that get this wrong). The workaround of adding dependencies to your projects is also manageable.

I recommend reporting this issue to those two libraries.

**Comment by lukaseder** [comment]
I mean, I could help you with the report or the analysis, but I'd have to have a reproducer first, ideally based on this template: https://github.com/jOOQ/jOOQ-mcve

**Comment by mnisius** [comment]
@lukaseder thank you. 

I created the reproducer based on your template. It's here: https://github.com/jOOQ/jOOQ-mcve/compare/main...mnisius:jOOQ-mcve:main

I already found a matching issue in die immutables project: https://github.com/immutables/immutables/issues/1529

**Comment by lukaseder** [comment]
`UDTPathFieldImpl` and `UDTPathTableFieldImpl` are also affected. We'll regression test this in our own code generation tests to be sure it doesn't get re-introduced. The annotation is still useful for other internal API, just not as base class of generated code.

**Comment by mnisius** [comment]
Oh that's very interesting. Thank you again for the investigation and the proposed solution.

**Comment by lukaseder** [comment]
This is actually a "regression" introduced with #228 in jOOQ 3.19 only. 3.18 and earlier aren't affected

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.19 (https://github.com/jOOQ/jOOQ/issues/17918)
