### ISSUE TITLE
JPADatabase codegen not working with Hibernate 6.4.1

### ISSUE THREAD

**Issue by barteksc** [jOOQ/jOOQ#16335]
### Expected behavior

Source code should be generated

### Actual behavior

When running `mvn clean package`, build fails with the following error:

```
Execution jooq-codegen of goal org.jooq:jooq-codegen-maven:3.19.4:generate failed: An API incompatibility was encountered while executing org.jooq:jooq-codegen-maven:3.19.4:generate: java.lang.NoSuchMethodError: 'void org.hibernate.tool.schema.spi.SchemaDropper.doDrop(org.hibernate.boot.Metadata, org.hibernate.tool.schema.spi.ExecutionOptions, org.hibernate.tool.schema.spi.SourceDescriptor, org.hibernate.tool.schema.spi.TargetDescriptor)'
```

### Steps to reproduce the problem

```xml
    <dependencies>
        <dependency>
            <groupId>org.jooq</groupId>
            <artifactId>jooq</artifactId>
            <version>3.19.4</version>
        </dependency>
        <dependency>
            <groupId>org.jooq</groupId>
            <artifactId>jooq-meta-extensions-hibernate</artifactId>
            <version>3.19.4</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.jooq</groupId>
                <artifactId>jooq-codegen-maven</artifactId>
                <version>3.19.4</version>

                <executions>
                    <execution>
                        <id>jooq-codegen</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                </executions>

                <configuration>
                    <generator>
                        <database>
                            <name>org.jooq.meta.extensions.jpa.JPADatabase</name>
                            <properties>
                                <property>
                                    <key>packages</key>
                                    <value>com.example.entities</value>
                                </property>
                                <property>
                                    <key>useAttributeConverters</key>
                                    <value>true</value>
                                </property>
                                <property>
                                    <key>unqualifiedSchema</key>
                                    <value>none</value>
                                </property>
                            </properties>
                        </database>
                    </generator>
                </configuration>
            </plugin>
        </plugins>
    </build>
```

### jOOQ Version

jOOQ Open Source 3.19.4

### Database product and version

MySQL 8.0.33

### Java Version

openjdk 17.0.8

**Comment by lukaseder** [comment]
Thanks for your message.

It should be possible to work around this by isolating the code generation classpath in a way not to override the `jooq-meta-extensions-hibernate`'s hibernate dependency, I think?

Other than that, I think this is just a duplicate of:

- https://github.com/jOOQ/jOOQ/issues/13721
