### ISSUE TITLE
Compilation error in generated code when both SchemaVersionProvider and CatalogVersionProvider are applied

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#6423]
Usually, it is not necessary to provide both `SchemaVersionProvider` and `CatalogVersionProvider`, but if people do, then the generated code will not compile due to a missing comma:

```java
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.8",
        "catalog version:DEFAULT_CATALOG_20170719114948" // missing comma here
        "schema version:FLYWAY_TEST_3"
    },
    date = "2017-07-19T09:49:48.723Z",
    comments = "This class is generated by jOOQ"
)
```

This is a regression introduced with #5649
