### ISSUE TITLE
in-memory enum types members are not sanitized

### ISSUE THREAD

**Issue by rkapl** [jOOQ/jOOQ#8555]
### Expected behavior and actual behavior:
When parsing  the code below using DDLDatabase:

    `state` enum('new', 'old')

an exception is thrown:

    Caused by: org.jooq.tools.reflect.ReflectException: Compilation error: /org/jooq/impl/GeneratedEnum2730208.java:3: error: <identifier> expected
	at org.jooq.tools.reflect.Compile.compile(Compile.java:88)
	at org.jooq.tools.reflect.Reflect.compile(Reflect.java:77)
	at org.jooq.impl.ParserImpl.parseDataTypeEnum(ParserImpl.java:7394)
        ....

There seems to be no way to turn off the in-memory type generation, introduced in #7386. There should be some kind of name sanitization as used in other cases.

### Versions:
- jOOQ: 3.11.11
- Database (include vendor): MariaDB + DDLDatabase

**Comment by lukaseder** [comment]
Thank you very much for your report. Indeed, the in-memory enums should go through something similar as the code generator's generator strategies. There are a few other cases where such a strategy would be useful at runtime, e.g. in the `DefaultRecordMapper`.

As far as enums are concerned, using in-memory compilation has been a workaround in order to produce a `java.lang.Enum` type just like the code generator. In fact, it would be better to have a jOOQ-specific enum API that does not depend on implementations being Java enums. This would also solve some issues we have in other languages, like Scala.

This issue here will probably solve itself once #7025 is implemented.

**Comment by lukaseder** [comment]
A similar case is:

```sql
CREATE TABLE y (e enum('', '-'));
```

**Comment by cghislai** [comment]
From java 9 on, `_` is a reserved keyword as well, and cannot be used as an enum constant

**Comment by lukaseder** [comment]
Thanks, @cghislai. That is a separate issue: https://github.com/jOOQ/jOOQ/issues/4703

**Comment by lukaseder** [comment]
This was much easier to fix than I thought. We don't care about the `Enum.name()` value of the generated enum type. We only need `EnumType.getLiteral()`. So with synthetic enum names, this could be fixed very easily.

Fixed for 3.13.0. Backport scheduled for 3.12.2 (#9287)
