### ISSUE TITLE
Regression: Date <-> Timestamp converter ignored after upgrading from 3.4.2 to 3.5

### ISSUE THREAD

**Issue by axelfontaine** [jOOQ/jOOQ#3823]
In my pom.xml jooq generator config I have this:

```
<database>
    <name>org.jooq.util.postgres.PostgresDatabase</name>
    <includes>.*</includes>
    <inputSchema>abc</inputSchema>
    <customTypes>
           <customType>
                  <name>BinaryEncrypted</name>
                  <type>byte[]</type>
                  <converter>abc.jooq.BinaryEncryptedConverter</converter>
           </customType>
           <customType>
                   <name>IntEncrypted</name>
                   <type>java.lang.Integer</type>
                   <converter>abc.jooq.IntEncryptedConverter</converter>
            </customType>
            <customType>
                    <name>Utf8Encrypted</name>
                    <type>java.lang.String</type>
                    <converter>abc.jooq.Utf8EncryptedConverter</converter>
             </customType>
             <customType>
                     <name>TimestampDate</name>
                     <type>java.util.Date</type>
                     <converter>abc.jooq.TimestampConverter</converter>
             </customType>
             ...
```

All worked fine in 3.4.2.

With the 3.5.0 upgrade (version bump in the pom, no other changes), the TimestampConverter started being ignored.

Here is the source:

```
public class TimestampConverter implements Converter<Timestamp, Date> {
    @Override
    public Date from(Timestamp databaseObject) {
        if (databaseObject == null) {
            return null;
        }
        return new Date(databaseObject.getTime());
    }

    @Override
    public Timestamp to(Date userObject) {
        if (userObject == null) {
            return null;
        }
        return new Timestamp(userObject.getTime());
    }

    @Override
    public Class<Timestamp> fromType() {
        return Timestamp.class;
    }

    @Override
    public Class<Date> toType() {
        return Date.class;
    }
}
```

This generator runs without errors, however now the compiler stumbles with:

```
[ERROR] /abc/Def.java:[31,35] incompatible types: java.util.Date cannot be converted to java.sql.Timestamp
[ERROR] /abc/Def.java:[61,46] no suitable method found for between(java.util.Date,java.util.Date)
[ERROR] method org.jooq.Field.between(java.sql.Timestamp,java.sql.Timestamp) is not applicable
[ERROR] (argument mismatch; java.util.Date cannot be converted to java.sql.Timestamp)
[ERROR] method org.jooq.Field.between(org.jooq.Field<java.sql.Timestamp>,org.jooq.Field<java.sql.Timestamp>) is not applicable
[ERROR] (argument mismatch; java.util.Date cannot be converted to org.jooq.Field<java.sql.Timestamp>)
[ERROR] /abc/Def.java:[29,75] no suitable method found for gt(java.util.Date)
[ERROR] method org.jooq.Field.gt(java.sql.Timestamp) is not applicable
[ERROR] (argument mismatch; java.util.Date cannot be converted to java.sql.Timestamp)
[ERROR] method org.jooq.Field.gt(org.jooq.Field<java.sql.Timestamp>) is not applicable
[ERROR] (argument mismatch; java.util.Date cannot be converted to org.jooq.Field<java.sql.Timestamp>)
[ERROR] method org.jooq.Field.gt(org.jooq.Select<? extends org.jooq.Record1<java.sql.Timestamp>>) is not applicable
[ERROR] (argument mismatch; java.util.Date cannot be converted to org.jooq.Select<? extends org.jooq.Record1<java.sql.Timestamp>>)
[ERROR] method org.jooq.Field.gt(org.jooq.QuantifiedSelect<? extends org.jooq.Record1<java.sql.Timestamp>>) is not applicable
[ERROR] (argument mismatch; java.util.Date cannot be converted to org.jooq.QuantifiedSelect<? extends org.jooq.Record1<java.sql.Timestamp>>)
```

Changing the version in the pom back to 3.4.2 fixes all errors.

**Comment by lukaseder** [comment]
This works again in jOOQ 3.10, probably because of the fix in #5872
