### ISSUE TITLE
Compilation errors in generated code for PostgreSQL's pg_catalog schema

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#7692]
When generating code for `pg_catalog` in PostgreSQL, there are several compilation errors in the output, whenever an unknown data type is encountered, e.g.:

```java
public final TableField<Record, Object[]> INDOPTION = createField("indoption", .getArrayDataType(), this, "");
//                                                                             ^ missing data type here
public final TableField<Record, Object> INDEXPRS = createField("indexprs", , this, "");
//                                                                         ^ missing data type here
```

Probably a regression caused by #7500

**Comment by lukaseder** [comment]
Fixed for jOOQ 3.12. Backport to 3.11.4 scheduled: #7695. 3.10 seems unaffected
