### ISSUE TITLE
Compilation error in generated code when a sequence name ends with $

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#3899]
This is a regression introduced with #3336 only in unpublished versions 3.6.0
