### ISSUE TITLE
Slash in name results in invalid identifier being generated using KotlinGenerator

### ISSUE THREAD

**Issue by joel-bach** [jOOQ/jOOQ#18473]
### Expected behavior

Only valid Kotlin identifiers are generated even if the database table / column / key name contains invalid characters.

### Actual behavior

At least the slash `/` in names is replicated in the identifiers in Kotlin, e.g. in the Keys.kt file created by the reproducer below:

```kotlin
// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val TEST2_PKEY: UniqueKey<Test2Record> = Internal.createUniqueKey(Test2.TEST2, DSL.name("test2_pkey"), arrayOf(Test2.TEST2.ID), true)
val `THIS / TABLE_PKEY`: UniqueKey<This_2fTableRecord> = Internal.createUniqueKey(reproducer.tables.This_2fTable.`THIS / TABLE`, DSL.name("this / table_pkey"), arrayOf(reproducer.tables.This_2fTable.`THIS / TABLE`.`THIS / ID`), true)

// -------------------------------------------------------------------------
// FOREIGN KEY definitions
// -------------------------------------------------------------------------

val `TEST2__IS / THIS POSSIBLE`: ForeignKey<Test2Record, This_2fTableRecord> = Internal.createForeignKey(Test2.TEST2, DSL.name("is / this possible"), arrayOf(Test2.TEST2.TEST_ID), reproducer.keys.`THIS / TABLE_PKEY`, arrayOf(reproducer.tables.This_2fTable.`THIS / TABLE`.`THIS / ID`), true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION)
```

When trying to compile using Kotlin 2.1.20 this leads to a `Name contains illegal characters` compilation error.

### Steps to reproduce the problem

The problem was noticed with the jOOQ Trial Edition and SQL Server with a larger database which contains foreign keys with slashes in their names but I was able to reproduce it with PostgreSQL and the Open Source Edition as well, Gradle configuration for the code generation and DDL used attached below.

build.gradle.kts
```kotlin
plugins {
    kotlin("jvm") version "2.1.20"
    id("org.jooq.jooq-codegen-gradle") version "3.20.4"
}

kotlin {
    jvmToolchain(21)
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("org.jooq:jooq:3.20.4")
    jooqCodegen("org.postgresql:postgresql:42.7.5")
}

jooq {
    configuration {
        jdbc {
            driver = "org.postgresql.Driver"
            url = "jdbc:postgresql://localhost:5555/backend"
            user = "backend"
            password = "backend"
        }
        generator {
            name = "org.jooq.codegen.KotlinGenerator"
            database {
                name = "org.jooq.meta.postgres.PostgresDatabase"
                inputSchema = "public"
            }
            target {
                packageName = "reproducer"
                directory = "src/main/kotlin-gen/jooq-gen"
            }
        }
    }
}
```

docker-compose.yml:
```yaml
services:
  backend-postgres:
    image: postgres:17
    ports:
      - 5555:5432
    environment:
      - POSTGRES_PASSWORD=backend
      - POSTGRES_USER=backend
      - POSTGRES_DB=backend
```

DDL for the example schema:
```sql
CREATE TABLE "this / table"
( 
  "this / id" SERIAL PRIMARY KEY,
  name TEXT
);

CREATE TABLE test2
( 
  id SERIAL PRIMARY KEY,
  test_id INTEGER
);

ALTER TABLE test2 ADD CONSTRAINT "is / this possible" FOREIGN KEY (test_id) REFERENCES "this / table" ("this / id");
```

### jOOQ Version

jOOQ Open Source Edition 3.20.4 (also tested with 3.19.22), jOOQ Trial Edition 3.20.4 (for SQL Server)

### Database product and version

"PostgreSQL 17.4 (Debian 17.4-1.pgdg120+2) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit" and "Microsoft SQL Server 2019 (RTM) - 15.0.2000.5 (X64)  	Sep 24 2019 13:48:23  	Copyright (C) 2019 Microsoft Corporation 	Express Edition (64-bit) on Windows 10 Pro 10.0 <X64> (Build 22000: ) (Hypervisor)"

### Java Version

openjdk version "21.0.7" 2025-04-15 LTS

### JDBC / R2DBC driver name and version (include name if unofficial driver)

"org.postgresql:postgresql:42.7.5" and "com.microsoft.sqlserver:mssql-jdbc:12.10.0.jre11"

**Comment by lukaseder** [comment]
Thanks for your report. You can work around this with a generator strategy:
https://www.jooq.org/doc/latest/manual/code-generation/codegen-object-naming/

**Comment by lukaseder** [comment]
Looking into this now. A related issue:

- https://github.com/jOOQ/jOOQ/issues/18641

**Comment by lukaseder** [comment]
Related:

- https://github.com/jOOQ/jOOQ/issues/17099

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.21.0
- 3.20.6 (https://github.com/jOOQ/jOOQ/issues/18644)
- 3.19.25 (https://github.com/jOOQ/jOOQ/issues/18645)
- 3.18.32 (https://github.com/jOOQ/jOOQ/issues/18646)

**Comment by lukaseder** [comment]
Also related:

- https://github.com/jOOQ/jOOQ/issues/18654
