### ISSUE TITLE
Duplicate methods generated in Routines class for table valued functions, if neither <tableValuedFunctionsAsRoutines/> nor <tableValuedFunctionsAsTables/> is turned off

### ISSUE THREAD

**Issue by jankoh** [jOOQ/jOOQ#19802]
### Expected behavior

We use Jooq with the Gradle plugin and automatic Code-Generation. W recently upgraded Jooq vom 3.20.11 to 3.21.0. Identical configuration now enexpectedly produces a compile-time error in the generated code.

Am I missing something crucial in the new version or is this a bug?

Thanks Jan

### Actual behavior

After upgrading Jooq vom 3.20.11 to 3.21.0 we get a compile error since one of our Database UDFs is generated twice in Routines.java:
```shell
/builds/team-elster/rv-tool/backend_supplier/build/generated/jooq/rv-tool/de/n4/rvtool/db_supplier/Routines.java:1565: error: method udfMeasureGetGroupedPosTable(Configuration,UUID) is already defined in class Routines
    public static Result<UdfMeasureGetGroupedPosTableRecord> udfMeasureGetGroupedPosTable(
                                                             ^
1 error
> Task :backend_supplier:compileJava FAILED
[Incubating] Problems report is available at: file:///builds/team-elster/rv-tool/build/reports/problems/problems-report.html
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':backend_supplier:compileJava'.
> Compilation failed; see the compiler output below.
  /builds/team-elster/rv-tool/backend_supplier/build/generated/jooq/rv-tool/de/n4/rvtool/db_supplier/Routines.java:1565: error: method udfMeasureGetGroupedPosTable(Configuration,UUID) is already defined in class Routines
      public static Result<UdfMeasureGetGroupedPosTableRecord> udfMeasureGetGroupedPosTable(
                                                               ^
  1 error
* Try:
> Check your code and dependencies to fix the compilation error(s)
> Run with --scan to get full insights from a Build Scan (powered by Develocity).
```

The UDF looks like the following:
```sql
create or replace function udf_measure_get_grouped_pos_table(
    measure_id_param bigint
)
returns table (
    rv_family_version_service_pos_id bigint,
    type_calc_meth varchar(64)
)
language plpgsql
stable as
$$
begin
    return query
        select
            mp.rv_family_version_service_pos_id, mp.type_calc_meth
        from measure_pos mp
        where
            mp.measure_id = measure_id_param
        group by
            mp.rv_family_version_service_pos_id, mp.type_calc_meth;
end;
$$;
```

The generated code in Routines.java is:
```java
/**
 * Convenience access to all stored procedures and functions in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Routines {

   ...

    /**
     * Call <code>public.udf_measure_get_grouped_pos_table</code>
     */
    public static UdfMeasureGetGroupedPosTable udfMeasureGetGroupedPosTable(
          Configuration configuration
        , Long measureIdParam
    ) {
        UdfMeasureGetGroupedPosTable p = new UdfMeasureGetGroupedPosTable();
        p.setMeasureIdParam(measureIdParam);

        p.execute(configuration);
        return p;
    }

    ...

    /**
     * Call <code>public.udf_measure_get_grouped_pos_table</code>.
     */
    public static Result<UdfMeasureGetGroupedPosTableRecord> udfMeasureGetGroupedPosTable(
          Configuration configuration
        , Long measureIdParam
    ) {
        return configuration.dsl().selectFrom(de.n4.rvtool.db.tables.UdfMeasureGetGroupedPosTable.UDF_MEASURE_GET_GROUPED_POS_TABLE.call(
              measureIdParam
        )).fetch();
    }
}
```

### Steps to reproduce the problem

1. Update to 3.21.0
2. Execute Build

### jOOQ Version

3.21.0

### Database product and version

PostgreSQL

### Java Version

openjdk version "25.0.2" 2026-01-20

### JDBC / R2DBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.7.10

**Comment by lukaseder** [comment]
Thanks for your report.

This doesn't manifest in our integration tests, but it's likely that something went wrong with:

- #17713

The issue also hints how you can work around the problem, by removing one of the two variants again from code generation output.

**Comment by lukaseder** [comment]
The regression happens because the default for both new flags `<tableValuedFunctionsAsRoutines/>` and `<tableValuedFunctionsAsTables/>` is `true`. The workaround is to turn off one of the flags for now.

**Comment by lukaseder** [comment]
The fix is to give preference to the table valued function code generation over the routine code generation in the `Routines` class, as the former exposes a more powerful return type than the latter, and they're functionally equivalent.

The main purpose of #17713 is to offer defaulted parameter support for TVFs, and that's available only in the generated `Routine` class anyway, not in the `Routines` convenience methods.

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.22.0
- 3.21.1 (https://github.com/jOOQ/jOOQ/issues/19808)
