### ISSUE TITLE
Generated field for PostgreSQL Timestamp cannot compile on jOOQ 3.14

### ISSUE THREAD

**Issue by DOFandersolsen** [jOOQ/jOOQ#11175]
### Expected behavior

Generated code can compile and run, just like on jOOQ 3.12 and jOOQ 3.12

### Actual behavior

When generating code during `mvn spring-boot:run`, it fails with error "java: cannot find symbol" but only on 3.14, it works on all versions for 3.12 and 3.13

### Steps to reproduce the problem

Code generated using previous jOOQ versions:

**3.12.3** (The version I am upgrading from): 
```java
public final TableField<ImageRecord, LocalDateTime> UPLOADED = createField(DSL.name("uploaded"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, ""); 
```
**3.13.6:**
```java
public final TableField<ImageRecord, LocalDateTime> UPLOADED = createField(DSL.name("uploaded"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");
```

**3.14.4:**
```java
public final TableField<ImageRecord, LocalDateTime> UPLOADED = createField(DSL.name("uploaded"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");
```` 

Notice the (6) after LOCALDATETIME in 3.14.
This is reproducible in all 3.14 versions

Maven code-gen config:
```xml
<plugin>
  <groupId>org.jooq</groupId>
  <artifactId>jooq-codegen-maven</artifactId>
  <version>3.14.4</version>
  
  <!-- The plugin should hook into the generate goal -->
  <executions>
	  <execution>
		  <goals>
			  <goal>generate</goal>
		  </goals>
	  </execution>
  </executions>
  
  <!-- Specify the plugin configuration.
                   The configuration format is the same as for the standalone code generator -->
  <configuration>
  
	  <!-- A boolean property (or constant) can be specified here to tell the plugin not to do anything -->
	  <skip>${skip.jooq.generation}</skip>
  
	  <!-- JDBC connection parameters -->
	  <jdbc>
		  <driver>org.postgresql.Driver</driver>
		  <url>jdbc:postgresql:test</url>
		  <user>test</user>
		  <password>test</password>
	  </jdbc>
  
	  <!-- Generator parameters -->
	  <generator>
		  <generate>
			  <javaTimeTypes>true</javaTimeTypes>
		  </generate>
		  <database>
			  <name>org.jooq.meta.postgres.PostgresDatabase</name>
			  <includes>.*</includes>
			  <excludes></excludes>
			  <inputSchema>test</inputSchema>
		  </database>
		  <target>
			  <packageName>org.example.test.db</packageName>
			  <directory>src/main/java</directory>
		  </target>
	  </generator>
  </configuration>
</plugin>
```

PostgreSQL table structure from `pg_dump`:
```sql
CREATE TABLE test.image (
    id integer NOT NULL,
    filename text NOT NULL,
    path text NOT NULL,
    uploaded timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    comment text
);
````

### Versions

- jOOQ: 3.14.4
- Java: 11.0.2
- Database (include vendor): psql (PostgreSQL) 12.5 (Ubuntu 12.5-0ubuntu0.20.04.1) (through WSL)
- OS: Windows 10
- JDBC Driver (include name if inofficial driver): `org.postgresql.Driver`

**Comment by lukaseder** [comment]
Thank you very much for your report.

The method is where you'd expect it to be:
https://www.jooq.org/javadoc/3.14.x/org.jooq/org/jooq/impl/SQLDataType.html#LOCALDATETIME(int)

You're probably just not using 3.14 (the runtime library), a common issue when using Spring Boot which has default jOOQ version dependencies, see the FAQ:
https://www.jooq.org/faq

Or this article:
https://blog.jooq.org/2019/06/26/how-to-use-jooqs-commercial-distributions-with-spring-boot/

**Comment by DOFandersolsen** [comment]
I feel silly for not realizing this, thank you for your quick answer :-)

**Comment by lukaseder** [comment]
No worries. It's really quite a frequent issue, so you're not alone :)
